pipeline {
  agent {
    node {
      label 'base'
    }

  }
  stages {
    stage('build and tag image') {
      steps {
        container('base') {
          sh '''docker build -t gruporawer/builder-base .
docker tag gruporawer/builder-base gruporawer/builder-base:1.0.0'''
        }

      }
    }
    stage('docker push') {
      when{
        branch 'master'
      }
      steps {
        container('base') {
          withCredentials([usernamePassword(passwordVariable : 'DOCKER_PASSWORD' ,usernameVariable : 'DOCKER_USERNAME' ,credentialsId : 'dockerhub-id' ,)]) {
            sh 'echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin'
          }
            sh 'docker push gruporawer/builder-base'
        }
      }
    }
    stage('update language image'){
      when{
        branch 'master'
      }
      steps{
         build job:'../builder-nodejs/master', wait: false
      }
    }
  }
}
